# coding: utf-8

"""
    Content and Auth API

    Sbermarket API для мерчантов и ресторанов.  Позволяет управлять: - ассортиментом товаров; - меню; - остатками товаров в магазинах; - доступностью блюд; - ценами и акциями на товары и блюда.  Базовый URL для запросов: `https://merchant-api.sbermarket.ru`  API для мерчантов для получения access tokens. # Порядок работы 1. Получить access token, выполнив POST /auth/token по oAuth 2.0 flow (client credentials)

    The version of the OpenAPI document: 0.0.2a
    Contact: merchant.api@sbermarket.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sm_content_api.models.import_categories_request import ImportCategoriesRequest

class TestImportCategoriesRequest(unittest.TestCase):
    """ImportCategoriesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportCategoriesRequest:
        """Test ImportCategoriesRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportCategoriesRequest`
        """
        model = ImportCategoriesRequest()
        if include_optional:
            return ImportCategoriesRequest(
                data = [
                    sm_content_api.models.category.Category(
                        id = '100', 
                        name = 'Сыры', 
                        parent_id = '1', 
                        position = 1, 
                        status = 'ACTIVE', )
                    ]
            )
        else:
            return ImportCategoriesRequest(
                data = [
                    sm_content_api.models.category.Category(
                        id = '100', 
                        name = 'Сыры', 
                        parent_id = '1', 
                        position = 1, 
                        status = 'ACTIVE', )
                    ],
        )
        """

    def testImportCategoriesRequest(self):
        """Test ImportCategoriesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
