# coding: utf-8

"""
    Content and Auth API

    Sbermarket API для мерчантов и ресторанов.  Позволяет управлять: - ассортиментом товаров; - меню; - остатками товаров в магазинах; - доступностью блюд; - ценами и акциями на товары и блюда.  Базовый URL для запросов: `https://merchant-api.sbermarket.ru`  API для мерчантов для получения access tokens. # Порядок работы 1. Получить access token, выполнив POST /auth/token по oAuth 2.0 flow (client credentials)

    The version of the OpenAPI document: 0.0.2a
    Contact: merchant.api@sbermarket.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sm_content_api.api.import_api import ImportApi


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportApi()

    def tearDown(self) -> None:
        pass

    def test_import_availability(self) -> None:
        """Test case for import_availability

        Указать доступность товаров/блюд
        """
        pass

    def test_import_categories(self) -> None:
        """Test case for import_categories

        Создать или обновить категорию товаров
        """
        pass

    def test_import_offers(self) -> None:
        """Test case for import_offers

        Создать или обновить товар
        """
        pass

    def test_import_options_groups(self) -> None:
        """Test case for import_options_groups

        Создать или обновить наборы опций блюд (для ресторанов)
        """
        pass

    def test_import_prices(self) -> None:
        """Test case for import_prices

        Обновить цену товаров
        """
        pass

    def test_upload_offer_image(self) -> None:
        """Test case for upload_offer_image

        Загружает изображение товара (оффера)
        """
        pass


if __name__ == '__main__':
    unittest.main()
