# coding: utf-8

"""
    Content API

    API для мерчантов и ресторанов.  Позволяет управлять: - ассортиментом товаров; - меню; - остатками товаров в магазинах; - доступностью блюд; - ценами и акциями на товары и блюда.  Базовый URL для запросов: `https://merchant-api.sbermarket.ru`

    The version of the OpenAPI document: 0.0.2
    Contact: merchant.api@sbermarket.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sm_content_api.models.stock import Stock


class TestStock(unittest.TestCase):
    """Stock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self) -> Stock:
        """Test Stock
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        return Stock(
            offer_id = '1001',
            outlet_id = '2',
            stock = '10'
        )

    def testStock(self):
        """Test Stock"""
        inst_req_only = self.make_instance()


if __name__ == '__main__':
    unittest.main()
