# coding: utf-8

"""
    Content and Auth API

    Sbermarket API для мерчантов и ресторанов.  
    Позволяет управлять: 
        - ассортиментом товаров; 
        - меню; 
        - остатками товаров в магазинах; 
        - доступностью блюд; 
        - ценами и акциями на товары и блюда.  
    Базовый URL для запросов: `https://merchant-api.sbermarket.ru`  
    
    API для мерчантов для получения access tokens. 
        # Порядок работы 
            1. Получить access token, выполнив POST /auth/token по oAuth 2.0 flow (client credentials)

    Stores API

    API для мерчантов для управления своими торговыми точками   
    # Порядок работы с Stores API  
    1. Получить access token, выполнив (POST /auth/token) аутентификацию по oAuth 2.0 flow (client credentials) 
    2. Получить список своих торговых точек выполнив запрос /retail-chains/{retail_chain_slug}/stores     
        - Где retail_chain_slug это идентификатор сети мерчанта полученный в СберМаркете     
        - Этот запрос возвращает постраничный список ваших stores, зарегистрированных в СберМаркете     
        - В поле \"id\" находится идентификатор store в системе СберМеркет     
        - В поле \"merchant_store_id\" находится идентификатор store в системе мерчанта       
        - Для получения или изменения данных по торговой точке необходимо предоставлять этот идентификатор 
          (merchant_store_id в пути к ресурсу) 
    3. Указать дополнительные данные по торговой точке, которые зависят от типа интеграции с СберМаркетом 
       и вида торговой точки:     
        - при доставке мерчантом:       
        - PUT /retail-chains/{retail_chain_slug}/stores/{merchant_store_id}/merchant-status 
          (изменение статуса магазина)         
        - чтобы узнать текущий статус store в приложении СберМаркет используйте 
          GET /retail-chains/{retail_chain_slug}/stores/{merchant_store_id}           
          в поле sm_status.status указано доступен ли этот store в приложении СберМаркет для новых заказов     


    The version of the OpenAPI document: 0.0.3a
    Contact: merchant.api@sbermarket.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "sm-content-api"
VERSION = "0.2.0"
PYTHON_REQUIRES = ">=3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="SberMarket Content and Auth API",
    author="Oleg Fish",
    author_email="okfish@yandex.ru",
    url="",
    keywords=["OpenAPI", "aiohttp", "asyncio", "Sbermarket Content and Auth API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Sbermarket API для мерчантов и ресторанов.  Позволяет управлять: - ассортиментом товаров; - меню; - остатками товаров в магазинах; - доступностью блюд; - ценами и акциями на товары и блюда.  Базовый URL для запросов: &#x60;https://merchant-api.sbermarket.ru&#x60;  API для мерчантов для получения access tokens. # Порядок работы 1. Получить access token, выполнив POST /auth/token по oAuth 2.0 flow (client credentials)
    """,  # noqa: E501
    package_data={"sm_content_api": ["py.typed"]},
)
