# coding: utf-8

"""
    Content and Auth API

    Sbermarket API для мерчантов и ресторанов.  
    Позволяет управлять: 
        - ассортиментом товаров; 
        - меню; 
        - остатками товаров в магазинах; 
        - доступностью блюд; 
        - ценами и акциями на товары и блюда.  
    Базовый URL для запросов: `https://merchant-api.sbermarket.ru`  
    
    API для мерчантов для получения access tokens. 
        # Порядок работы 
            1. Получить access token, выполнив POST /auth/token по oAuth 2.0 flow (client credentials)

    The version of the OpenAPI document: 0.0.2a
    Contact: merchant.api@sbermarket.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "sm-content-api"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">=3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="SberMarket Content and Auth API",
    author="Oleg Fish",
    author_email="okfish@yandex.ru",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Sbermarket Content and Auth API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Sbermarket API для мерчантов и ресторанов.  Позволяет управлять: - ассортиментом товаров; - меню; - остатками товаров в магазинах; - доступностью блюд; - ценами и акциями на товары и блюда.  Базовый URL для запросов: &#x60;https://merchant-api.sbermarket.ru&#x60;  API для мерчантов для получения access tokens. # Порядок работы 1. Получить access token, выполнив POST /auth/token по oAuth 2.0 flow (client credentials)
    """,  # noqa: E501
    package_data={"sm_content_api": ["py.typed"]},
)
