# coding: utf-8

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated

from sm_content_api.models.get_store200_response import GetStore200Response
from sm_content_api.models.get_stores200_response import GetStores200Response

from sm_content_api.api_client import ApiClient, RequestSerialized
from sm_content_api.api_response import ApiResponse
from sm_content_api.rest import RESTResponseType
from sm_content_api.auth import refresh_expired_token


class StoresApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    @refresh_expired_token()
    async def get_store(
        self,
        retail_chain_slug: Annotated[str, Field(strict=True, description="Человекочитаемый идентификатор торговой сети мерчанта")],
        merchant_store_id: Annotated[StrictStr, Field(description="идентификатор торговой точки мерчанта")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetStore200Response:
        """Информация об одной торговой точке

        Запрос на получение информации торговой точки

        :param retail_chain_slug: Человекочитаемый идентификатор торговой сети мерчанта (required)
        :type retail_chain_slug: str
        :param merchant_store_id: идентификатор торговой точки мерчанта (required)
        :type merchant_store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_store_serialize(
            retail_chain_slug=retail_chain_slug,
            merchant_store_id=merchant_store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetStore200Response",
            '400': "CommonDataObjectsProblemDetailsV1",
            '422': "CommonDataObjectsProblemDetailsV1",
            '429': "CommonDataObjectsProblemDetailsV1",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def get_store_with_http_info(
        self,
        retail_chain_slug: Annotated[str, Field(strict=True, description="Человекочитаемый идентификатор торговой сети мерчанта")],
        merchant_store_id: Annotated[StrictStr, Field(description="идентификатор торговой точки мерчанта")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetStore200Response]:
        """Информация об одной торговой точке

        Запрос на получение информации торговой точки

        :param retail_chain_slug: Человекочитаемый идентификатор торговой сети мерчанта (required)
        :type retail_chain_slug: str
        :param merchant_store_id: идентификатор торговой точки мерчанта (required)
        :type merchant_store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_store_serialize(
            retail_chain_slug=retail_chain_slug,
            merchant_store_id=merchant_store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetStore200Response",
            '400': "CommonDataObjectsProblemDetailsV1",
            '422': "CommonDataObjectsProblemDetailsV1",
            '429': "CommonDataObjectsProblemDetailsV1",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def get_store_without_preload_content(
        self,
        retail_chain_slug: Annotated[str, Field(strict=True, description="Человекочитаемый идентификатор торговой сети мерчанта")],
        merchant_store_id: Annotated[StrictStr, Field(description="идентификатор торговой точки мерчанта")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Информация об одной торговой точке

        Запрос на получение информации торговой точки

        :param retail_chain_slug: Человекочитаемый идентификатор торговой сети мерчанта (required)
        :type retail_chain_slug: str
        :param merchant_store_id: идентификатор торговой точки мерчанта (required)
        :type merchant_store_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_store_serialize(
            retail_chain_slug=retail_chain_slug,
            merchant_store_id=merchant_store_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetStore200Response",
            '400': "CommonDataObjectsProblemDetailsV1",
            '422': "CommonDataObjectsProblemDetailsV1",
            '429': "CommonDataObjectsProblemDetailsV1",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_store_serialize(
        self,
        retail_chain_slug,
        merchant_store_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if retail_chain_slug is not None:
            _path_params['retail_chain_slug'] = retail_chain_slug
        if merchant_store_id is not None:
            _path_params['merchant_store_id'] = merchant_store_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'oAuth2ClientCredentials'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/retail-chains/{retail_chain_slug}/stores/{merchant_store_id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    @refresh_expired_token()
    async def get_stores(
        self,
        retail_chain_slug: Annotated[str, Field(strict=True, description="Человекочитаемый идентификатор торговой сети мерчанта")],
        max_page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Количество результатов на странице вывода")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Токен для получения следующей страницы с результатами")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetStores200Response:
        """Список своих торговых точек

        Запрос на получение списка своих торговых точек

        :param retail_chain_slug: Человекочитаемый идентификатор торговой сети мерчанта (required)
        :type retail_chain_slug: str
        :param max_page_size: Количество результатов на странице вывода
        :type max_page_size: int
        :param page_token: Токен для получения следующей страницы с результатами
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_stores_serialize(
            retail_chain_slug=retail_chain_slug,
            max_page_size=max_page_size,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetStores200Response",
            '400': "CommonDataObjectsProblemDetailsV1",
            '422': "CommonDataObjectsProblemDetailsV1",
            '429': "CommonDataObjectsProblemDetailsV1",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def get_stores_with_http_info(
        self,
        retail_chain_slug: Annotated[str, Field(strict=True, description="Человекочитаемый идентификатор торговой сети мерчанта")],
        max_page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Количество результатов на странице вывода")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Токен для получения следующей страницы с результатами")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetStores200Response]:
        """Список своих торговых точек

        Запрос на получение списка своих торговых точек

        :param retail_chain_slug: Человекочитаемый идентификатор торговой сети мерчанта (required)
        :type retail_chain_slug: str
        :param max_page_size: Количество результатов на странице вывода
        :type max_page_size: int
        :param page_token: Токен для получения следующей страницы с результатами
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_stores_serialize(
            retail_chain_slug=retail_chain_slug,
            max_page_size=max_page_size,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetStores200Response",
            '400': "CommonDataObjectsProblemDetailsV1",
            '422': "CommonDataObjectsProblemDetailsV1",
            '429': "CommonDataObjectsProblemDetailsV1",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def get_stores_without_preload_content(
        self,
        retail_chain_slug: Annotated[str, Field(strict=True, description="Человекочитаемый идентификатор торговой сети мерчанта")],
        max_page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Количество результатов на странице вывода")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Токен для получения следующей страницы с результатами")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Список своих торговых точек

        Запрос на получение списка своих торговых точек

        :param retail_chain_slug: Человекочитаемый идентификатор торговой сети мерчанта (required)
        :type retail_chain_slug: str
        :param max_page_size: Количество результатов на странице вывода
        :type max_page_size: int
        :param page_token: Токен для получения следующей страницы с результатами
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_stores_serialize(
            retail_chain_slug=retail_chain_slug,
            max_page_size=max_page_size,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetStores200Response",
            '400': "CommonDataObjectsProblemDetailsV1",
            '422': "CommonDataObjectsProblemDetailsV1",
            '429': "CommonDataObjectsProblemDetailsV1",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_stores_serialize(
        self,
        retail_chain_slug,
        max_page_size,
        page_token,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if retail_chain_slug is not None:
            _path_params['retail_chain_slug'] = retail_chain_slug
        # process the query parameters
        if max_page_size is not None:
            
            _query_params.append(('max_page_size', max_page_size))
            
        if page_token is not None:
            
            _query_params.append(('page_token', page_token))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'oAuth2ClientCredentials'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/retail-chains/{retail_chain_slug}/stores',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


